### ISSUE TITLE
Issue Loading MR's - version 0.1.14

### ISSUE THREAD

**Issue by pvitty** [loblaw-sre/backstage-plugin-gitlab#20]
Hi, I'm trying to use your plugin, but I keep running into this error which I believe is related to MR's.

![image](https://user-images.githubusercontent.com/793695/136912390-a9bd1090-a054-48ff-905d-d78a5ec8f2dd.png)

```
TypeError: Cannot read properties of undefined (reading 'map')
    at DenseTable$1 (webpack-internal:///../../node_modules/@loblaw/backstage-plugin-gitlab/dist/index.esm.js:1783:35)
    at renderWithHooks (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:14804:18)
    at mountIndeterminateComponent (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:17483:13)
    at beginWork (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:18597:16)
    at HTMLUnknownElement.callCallback (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:189:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:238:16)
    at invokeGuardedCallback (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:293:31)
    at beginWork$1 (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:23204:7)
    at performUnitOfWork (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:22158:12)
    at workLoopSync (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:22131:22)
```

**Comment by satrox28** [comment]
Hi @pvitty 

We tried to reproduce and didn't see any error.

Have you setup the Gitlab Integration and Proxy configuration as below.

Add integration: In app-config.yaml add the integration for gitlab:
```integrations:
  gitlab:
    - host: gitlab.com
      token: ${GITLAB_TOKEN}```
Add proxy config:
```  '/gitlabci':
    target: '${GITLAB_URL}/api/v4'
    allowedMethods: ['GET']
    headers:
      PRIVATE-TOKEN: '${GITLAB_TOKEN}'```

**Comment by satrox28** [comment]
@pvitty closing the issue as no response. Feel free to reopen if you are still having issue.
